apiVersion: v1
kind: Service
metadata:
  name: coworking-space
spec:
  selector:
    app.kubernetes.io/name: coworking-space
  ports:
  - name: "5050"
    protocol: TCP
    port: 5050
    targetPort: 5050