apiVersion: v1
kind: Service
metadata:
  name: coworking-space
spec:
  selector:
    app.kubernetes.io/name: coworking-space
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-space
  labels:
    name: coworking-space
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking-space
  template:
    metadata:
      labels:
        service: coworking-space
    spec:
      containers:
        - name: coworking-space
          image: "506327011578.dkr.ecr.us-east-1.amazonaws.com/tienvq:0.0.2"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: "/readiness_check"
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
      restartPolicy: Always